name: Continuous Integration
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest      # Sets the build environment a machine with the latest Ubuntu installed
    steps:
    - uses: actions/checkout@v2 # Adds a step to checkout the repository code
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: C# build
      run: dotnet build
    - name: C# tests
      run: dotnet test
    - name: Install web dependencies
      run: npm install
      working-directory: DotnetTemplate.Web
    - name: Web build
      run: npm run build
      working-directory: DotnetTemplate.Web
    - name: TypeScript linting
      run: npm run lint
      working-directory: DotnetTemplate.Web
    - name: Web tests
      run: npm t
      working-directory: DotnetTemplate.Web